# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test
    - uses: actions/upload-artifact@v2
      with:
        name: 16.x
        path: dist/
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: 'release'
        path: 'release'
    - name: sync
      run: |
        export GIT_COMMIT_MESSAGE=$(git show -s --format=%s HEAD)
        echo "${GIT_COMMIT_MESSAGE}"
        cp dist/index* release/
        cd release
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add index*
        git commit -m "${GIT_COMMIT_MESSAGE}" || exit 0
        git push -u origin release
